interface Name {
    id: number;
    name: string;
    gender: Gender;
    popularity: Popularity;
    length: Length;
  }

enum Gender {
    BOY = "boy",
    GIRL = "girl",
  }
  
  enum Popularity {
    TRENDY = "trendy",
    UNIQUE = "unique",
  }
  enum Length {
    SHORT = "short",
    ALL = "all",
    LONG = "long",
  }




 const names: Name[] = [
    {
      id: 1,
      name: "Jakub",
      gender: Gender.BOY,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 2,
      name: "Adam",
      gender: Gender.BOY,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 3,
      name: "Samuel",
      gender: Gender.BOY,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 4,
      name: "Michal",
      gender: Gender.BOY,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 5,
      name: "Oliver",
      gender: Gender.BOY,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 6,
      name: "Tomáš",
      gender: Gender.BOY,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 7,
      name: "Filip",
      gender: Gender.BOY,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 8,
      name: "Matej",
      gender: Gender.BOY,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 9,
      name: "Lukáš",
      gender: Gender.BOY,
      popularity: Popularity.TRENDY,
      length: Length.LONG
      ,
    },
    {
      id: 10,
      name: "Martin",
      gender: Gender.BOY,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 11,
      name: "Richard",
      gender: Gender.BOY,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 12,
      name: "Alex",
      gender: Gender.BOY,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 13,
      name: "Matúš",
      gender: Gender.BOY,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
  
    {
      id: 14,
      name: "Tobias",
      gender: Gender.BOY,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 15,
      name: "Dávid",
      gender: Gender.BOY,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 16,
      name: "Peter",
      gender: Gender.BOY,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 17,
      name: "Šimon",
      gender: Gender.BOY,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 18,
      name: "Patrik",
      gender: Gender.BOY,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 19,
      name: "Dominik",
      gender: Gender.BOY,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 20,
      name: "Ján",
      gender: Gender.BOY,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 21,
      name: "Ema",
      gender: Gender.GIRL,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 22,
      name: "Nina",
      gender: Gender.GIRL,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 23,
      name: "Sofia",
      gender: Gender.GIRL,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 24,
      name: "Eliška",
      gender: Gender.GIRL,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 25,
      name: "Viktória",
      gender: Gender.GIRL,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 26,
      name: "Sára",
      gender: Gender.GIRL,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
  
    {
      id: 27,
      name: "Natália",
      gender: Gender.GIRL,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 28,
      name: "Nela",
      gender: Gender.GIRL,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 29,
      name: "Mia",
      gender: Gender.GIRL,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 30,
      name: "Hana",
      gender: Gender.GIRL,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 31,
      name: "Tamara",
      gender: Gender.GIRL,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 32,
      name: "Karolína",
      gender: Gender.GIRL,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
  
    {
      id: 33,
      name: "Kristína",
      gender: Gender.GIRL,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
  
    {
      id: 34,
      name: "Anna",
      gender: Gender.GIRL,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 35,
      name: "Diana",
      gender: Gender.GIRL,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 36,
      name: "Laura",
      gender: Gender.GIRL,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 37,
      name: "Olívia",
      gender: Gender.GIRL,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 38,
      name: "Michaela",
      gender: Gender.GIRL,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 39,
      name: "Rebeka",
      gender: Gender.GIRL,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 40,
      name: "Júlia",
      gender: Gender.GIRL,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
        id: 41,
        name: "Ernest",
        gender: Gender.BOY,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 42,
        name: "Drahoslav",
        gender: Gender.BOY,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 43,
        name: "Severín",
        gender: Gender.BOY,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 44,
        name: "Dobroslav",
        gender: Gender.BOY,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 45,
        name: "Gejza",
        gender: Gender.BOY,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 46,
        name: "Alfonz",
        gender: Gender.BOY,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 47,
        name: "Gašpar",
        gender: Gender.BOY,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 48,
        name: "Radomír",
        gender: Gender.BOY,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 49,
        name: "Frederik",
        gender: Gender.BOY,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 50,
        name: "Alan",
        gender: Gender.BOY,
        popularity: Popularity.UNIQUE,
        length: Length.SHORT,
    },
    {
        id: 51,
        name: "Arpád",
        gender: Gender.BOY,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 52,
        name: "Dezider",
        gender: Gender.BOY,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 53,
        name: "Fridrich",
        gender: Gender.BOY,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 54,
        name: "Kazimír",
        gender: Gender.BOY,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 55,
        name: "Oto",
        gender: Gender.BOY,
        popularity: Popularity.UNIQUE,
        length: Length.SHORT,
    },
    {
        id: 56,
        name: "Belo",
        gender: Gender.BOY,
        popularity: Popularity.UNIQUE,
        length: Length.SHORT,
    },
    {
        id: 57,
        name: "Vít",
        gender: Gender.BOY,
        popularity: Popularity.UNIQUE,
        length: Length.SHORT,
    },
    {
        id: 58,
        name: "Cyprián",
        gender: Gender.BOY,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 59,
        name: "Jerguš",
        gender: Gender.BOY,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 60,
        name: "Mojmír",
        gender: Gender.BOY,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 61,
        name: "Florián",
        gender: Gender.BOY,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 62,
        name: "Aurel",
        gender: Gender.BOY,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 63,
        name: "Žofia",
        gender: Gender.GIRL,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 64,
        name: "Natália",
        gender: Gender.GIRL,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 65,
        name: "Jela",
        gender: Gender.GIRL,
        popularity: Popularity.UNIQUE,
        length: Length.SHORT,
    },
    {
        id: 66,
        name: "Zina",
        gender: Gender.GIRL,
        popularity: Popularity.UNIQUE,
        length: Length.SHORT,
    },
    {
        id: 67,
        name: "Bohuslava",
        gender: Gender.GIRL,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 68,
        name: "Bohdana",
        gender: Gender.GIRL,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 69,
        name: "Nataša",
        gender: Gender.GIRL,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 70,
        name: "Valéria",
        gender: Gender.GIRL,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 71,
        name: "Anastázia",
        gender: Gender.GIRL,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 72,
        name: "Lea",
        gender: Gender.GIRL,
        popularity: Popularity.UNIQUE,
        length: Length.SHORT,
    },
    {
        id: 73,
        name: "Judita",
        gender: Gender.GIRL,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 74,
        name: "Vilma",
        gender: Gender.GIRL,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 75,
        name: "Hortenzia",
        gender: Gender.GIRL,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 76,
        name: "Rozália",
        gender: Gender.GIRL,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 77,
        name: "Sidónia	",
        gender: Gender.GIRL,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 78,
        name: "Milada",
        gender: Gender.GIRL,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 79,
        name: "Alica	",
        gender: Gender.GIRL,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 80,
        name: "Hermína",
        gender: Gender.GIRL,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 81,
        name: "Uršuľa",
        gender: Gender.GIRL,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
    {
        id: 82,
        name: "Albína",
        gender: Gender.GIRL,
        popularity: Popularity.UNIQUE,
        length: Length.LONG,
    },
      
  ];

  export {
    Gender,
    Popularity,
    Length,
    Name,
    names
  }